FROM java:8-jre

COPY GTFSLoader-1.0-SNAPSHOT-jar-with-dependencies.jar /opt/GTFSLoader/GTFSLoader-1.0-SNAPSHOT-jar-with-dependencies.jar
WORKDIR /opt/GTFSLoader


EXPOSE 4567

ENTRYPOINT ["java","-jar","GTFSLoader-1.0-SNAPSHOT-jar-with-dependencies.jar"]
CMD [""]

